testthat::test_that('advantage_plot returns a ggplot', {
  scores <- c(15, 5, 29, -94, 67, 76, 154, -31, 1000, 1000)
  p1 <- rbitr::advantage_plot(scores, scaling = 'none')
  testthat::expect_s3_class(p1, "ggplot")
  p1 <- rbitr::advantage_plot(scores, scaling = 'lichess')
  testthat::expect_s3_class(p1, "ggplot")
  p1 <- rbitr::advantage_plot(scores, scaling = 'regan')
  testthat::expect_s3_class(p1, "ggplot")
  p1 <- rbitr::advantage_plot(scores, style = 'infographic')
  testthat::expect_s3_class(p1, "ggplot")
})
