#' Evaluate a Chess Position
#'
#' Send a chess position to a chess engine for evaluation.
#'
#' @details The rbitr package relies on the bigchess package to handle the
#' interface with a Universal Chess Interface (UCI) compatible chess engine. An
#' engine handler must be created with `bigchess::uci_engine()` and passed to
#' the `evaluate_position()` function (see examples). See
#' wbec-ridderkerk.nl/html/UCIProtocol.html for details of the UCI protocol.
#'
#' @details Positions should be in long algebraic notation (LAN). The
#' `get_positions()` command will convert the movetext string from a pgn into a
#' series of positions in LAN, which can then be fed to `evaluate_position()`.
#'
#' @param position A single-element character vector of chess moves in long
#'   algebraic notation (LAN).
#' @param engine An engine handler generated by `bigchess::uci_engine()`.
#' @param n_pv A single-element integer vector of the desired number of
#'   principal variations.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @family engine tools
#'
#' @return The output of the chess engine as a character vector.
#' @export
#'
#' @examples
#' library(bigchess)
#' position <- 'e2e4 g7g5 b1c3'
#' engine_path <- '../../stockfish_13_win_x64_bmi2.exe'
#' engine <- uci_engine(engine_path)
#' evaluate_position(position, engine, n_pv = 1, depth = 1)
evaluate_position <- function (position, engine, n_pv, depth) {
  # Set the number of principal variations
  multipv_command <- paste('setoption name MultiPV value', n_pv, sep = ' ')
  engine <- bigchess::uci_cmd(engine, command = multipv_command)

  # Send position to chess engine and return the result
  engine <- bigchess::uci_ucinewgame(engine)
  engine <- bigchess::uci_isready(engine)
  engine <- bigchess::uci_cmd(
    engine,
    paste('position startpos moves', position, sep=' ')
  )
  engine <- bigchess::uci_isready(engine)
  engine <- bigchess::uci_go(engine, depth = depth)
  bigchess::uci_read(engine)$temp
}
