#' Evaluate Games
#'
#' @param games A list of games, where each game is a list of chess positions.
#' @param engine An engine handler generated by the bigchess function
#'   `uci_engine()`.
#' @param n_pv A single-element integer vector of the desired number of
#'   principal variations.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @return A recursive list of ucilogs.
#' @export
#'
#' @examples
#' games <- list(c('', 'e2e4', 'e2e4 g7g5', 'e2e4 g7g5 b1c3',
#'                 'e2e4 g7g5 b1c3 f7f5', 'e2e4 g7g5 b1c3 f7f5 d1h5'))
#' # Modify the path as required for your engine location & operating system
#' engine <- bigchess::uci_engine('//stockfish_13_win_x64_bmi2.exe')
#' evaluate_games(games, engine, n_pv = 1, depth = 1)
#' bigchess::uci_quit(engine)
evaluate_games <- function(games, engine, n_pv, depth) {
  # Set the number of principal variations
  multipv_command <- paste('setoption name MultiPV value', n_pv, sep = ' ')
  engine <- bigchess::uci_cmd(engine, command = multipv_command)
  evaluate_game <- function(game, engine, depth) {
    evaluate_position <- function(position, engine, depth) {
      # Send position to chess engine and return the result
      engine <- bigchess::uci_ucinewgame(engine)
      engine <- bigchess::uci_cmd(
        engine,
        paste('position startpos moves', position, sep = ' ')
      )
      engine <- bigchess::uci_go(engine, depth = depth)
      bigchess::uci_read(engine)$temp
    }
    lapply(game, evaluate_position, engine, depth)
  }
  lapply(games, evaluate_game, engine, depth)
}
