#' Evaluate each chess game in a pgn file.
#'
#' @details A wrapper for rbitr's `evaluate_game()` function that evaluates each
#'   game in the specified pgn file. Note that this can take a very long time
#'   for pgn files with a lot of games, and even longer when searching high
#'   numbers of principal variations and/or deep evaluations.
#'
#' @param pgn_path A single-element character vector of the path to the pgn.
#' @param engine An engine handler generated by the
#'   [bigchess](https://github.com/rosawojciech/bigchess) function
#'   `uci_engine()`.
#' @param n_pv A single-element integer vector of the desired number of
#'   principal variations.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @return A list. Each element of the list corresponds to a game in the pgn,
#'   and consists of a sublist containing the engine output for each position in
#'   that game.
#' @export
#'
#' @examples
#' library(bigchess)
#' # Modify engine_path as required for your engine location & operating system
#' engine_path <- '//stockfish_13_win_x64_bmi2.exe'
#' engine <- uci_engine(engine_path)
#' pgn_path <- file.path(
#'   system.file(package = 'rbitr'),
#'   'extdata',
#'   'fools_mate.pgn'
#' )
#' evaluate_pgn(pgn_path, engine, n_pv = 1, depth = 1)
evaluate_pgn <- function(pgn_path, engine, n_pv, depth) {
  # Validate input
  assertthat::assert_that(assertthat::is.string(pgn_path))
  assertthat::assert_that(class(engine$pipe)[1] == 'process')
  assertthat::assert_that(assertthat::is.count(n_pv))
  assertthat::assert_that(assertthat::is.count(depth))
  # Read the pgn
  pgn <- get_pgn(pgn_path)
  # Clean the movetext
  movetext <- clean_movetext(pgn$Movetext)
  lapply(movetext, evaluate_game, engine, n_pv, depth)
}
