#' Evaluate Chess Positions
#'
#' Send chess positions to a chess engine for evaluation.
#'
#' @details The rbitr package relies on the
#' [bigchess](https://github.com/rosawojciech/bigchess) package to handle the
#' interfaces to Universal Chess Interface (UCI) compatible chess engines. An
#' engine handler must be created with the bigchess `uci_engine()` function, and
#' the handler must then be passed to rbitr's `evaluate_positions()` function
#' (see examples). See
#' [the UCI protocol](http://wbec-ridderkerk.nl/html/UCIProtocol.html) for
#' details of UCI engine output.
#'
#' @details Positions should be in long algebraic notation (LAN). Games recorded
#'   in standard algebraic notation (SAN) can be converted to a series of
#'   positions in LAN using rbitr's `get_positions()` function, which can then
#'   be fed to `evaluate_positions()`.
#'
#' @param positions A character vector of chess positions in long algebraic
#'   notation (LAN).
#' @param engine An engine handler generated by the
#'   [bigchess](https://github.com/rosawojciech/bigchess) function
#'   `uci_engine()`.
#' @param n_pv A single-element integer vector of the desired number of
#'   principal variations.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @return A character vector of the engine output.
#' @export
#'
#' @examples
#' library(bigchess)
#' position <- 'e2e4 g7g5 b1c3'
#' # Modify the path as required for your engine location & operating system
#' engine_path <- '//stockfish_13_win_x64_bmi2.exe'
#' engine <- uci_engine(engine_path)
#' evaluate_positions(position, engine, n_pv = 1, depth = 1)
#' uci_quit(engine)
evaluate_positions <- function(positions, engine, n_pv, depth) {
  # Set the number of principal variations
  multipv_command <- paste('setoption name MultiPV value', n_pv, sep = ' ')
  engine <- bigchess::uci_cmd(engine, command = multipv_command)
  evaluate_position <- function(position, engine, depth) {
    # Send position to chess engine and return the result
    engine <- bigchess::uci_ucinewgame(engine)
    engine <- bigchess::uci_isready(engine)
    engine <- bigchess::uci_cmd(
      engine,
      paste('position startpos moves', position, sep = ' ')
    )
    engine <- bigchess::uci_isready(engine)
    engine <- bigchess::uci_go(engine, depth = depth)
    bigchess::uci_read(engine)$temp
  }
  lapply(positions, evaluate_position, engine, depth)
}
