#' Calculate centipawn loss.
#'
#' @param movetext A single element character vector containing a sequence of
#' moves in SAN.
#' @param engine An engine handler generated by the
#'   [bigchess](https://github.com/rosawojciech/bigchess) function
#'   `uci_engine()`.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @return An integer vector of centipawn loss for each move.
#' @export
#'
#' @examples
get_cpl <- function(movetext, engine, depth) {
  positions <- get_positions(movetext)[[1]]
  positions <- positions[1:(length(positions) - 1)]
  moves <- get_moves(movetext)[[1]]
  best_evaluations <- evaluate_games(positions, engine, n_pv = 1, depth)
  parsed_best_evals <- parse_eval_logs(best_evaluations)
  best_scores <- unlist(extract_eval(parsed_best_evals, 'scores'))
  played_evaluations <- search_moves(positions, moves, engine, depth)
  parsed_played_evals <- parse_ucilog(played_evaluations)
  played_scores <- unlist(lapply(parsed_played_evals, '[[', 'scores'), use.names = FALSE)
  as.integer(best_scores) - as.integer(played_scores)
}
