# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_engine_line_cpp <- function(engine_line, tag_names) {
    .Call('_rbitr_parse_engine_line_cpp', PACKAGE = 'rbitr', engine_line, tag_names)
}

