#' Search positions for the specified moves.
#'
#' Given a list of positions and a list of moves, search each position using
#' only the moves supplied for that position. Useful when you want to know an
#' engine's evaluation for specific moves that might not be principal
#' variations.
#'
#' @param positions A list of positions.
#' @param moves A list of moves.
#' @param engine An engine handler generated by the
#'   [bigchess](https://github.com/rosawojciech/bigchess) function
#'   `uci_engine()`.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @return A character vector of the engine output.
#' @export
#'
#' @examples
#' library(bigchess)
#' moves <- c("e2e4", "g7g5", "b1c3", "f7f5", "d1h5")
#' positions <- c( "", "e2e4", "e2e4 g7g5", "e2e4 g7g5 b1c3",
#'                 "e2e4 g7g5 b1c3 f7f5")
#' # Modify the path as required for your engine location & operating system
#' engine <- uci_engine('//stockfish_13_win_x64_bmi2.exe')
#' search_moves(positions, moves, engine, depth = 1)
#' uci_quit(engine)
search_moves <- function(positions, moves, engine, depth) {
  index <- 1:length(positions)
  move_search <- function(index, positions, moves, engine, depth) {
    search_move(positions[[index]], moves[[index]], engine, depth)
  }
  lapply(index, move_search, positions, moves, engine, depth)
}
