#' Search specific moves.
#'
#' @param position A character vector of a chess position in long algebraic
#'   notation (LAN).
#' @param move A character vector of moves to search.
#' @param engine An engine handler generated by the
#'   [bigchess](https://github.com/rosawojciech/bigchess) function
#'   `uci_engine()`.
#' @param depth A single-element integer vector of the desired search depth, in
#'   plies.
#'
#' @return A character vector of the engine output.
#' @export
#'
#' @examples
#' library(bigchess)
#' # Modify the path as required for your engine location & operating system
#' engine <- bigchess::uci_engine('//stockfish_13_win_x64_bmi2.exe')
#' search_move('', 'h2h3', engine = engine, depth = 1)
#' uci_quit(engine)
search_move <- function(position, move, engine, depth) {
  pv_command <- 'setoption name MultiPV value 1'
  engine <- bigchess::uci_cmd(engine, command = pv_command)
  position_command <- paste('position startpos moves', position)
  engine <- bigchess::uci_cmd(engine, position_command)
  go_command <- paste('go depth', depth, 'searchmoves', move)
  engine <- bigchess::uci_cmd(engine, command = go_command)
  engine <- bigchess::uci_isready(engine)
  bigchess::uci_read(engine)$temp
}
